title: 'Desarrollo de Sistemas Informáticos'
subtitle: 'Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2019/2020'
theme: jekyll-theme-midnight
#theme: jekyll-theme-time-machine
# theme: jekyll-theme-hacker
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate fatal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-leap-day
description: '3º. 2 cuatrimestre. Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2019/2020'
acronym: DSI-1920
future: true
show_downloads: false
teacher: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
campus_virtual: https://campusvirtual.ull.es/1920/course/view.php?id=201911055
github_classroom: https://classroom.github.com/classrooms/53047716-ull-esit-dsi-1920
exclude: 
  - tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-filesystem-ch2/ 
  - tema2-async/practicas/p6-t2-microservices/eval/
  - tema3-web/practicas/p8-t3-sessions-and-modules/resources/
