title: 'Desarrollo de Sistemas Informáticos'
subtitle: 'Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
theme: jekyll-theme-midnight
#theme: jekyll-theme-time-machine
# theme: jekyll-theme-hacker
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate fatal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-leap-day
description: '3º. 2 cuatrimestre. Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2018/2019'
future: true
show_downloads: false
exclude: 
  - tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-filesystem-ch2/ 
  - tema2-async/practicas/p6-t2-microservices/eval/
  - tema3-web/practicas/p8-t3-sessions-and-modules/resources/
