title: 'Desarrollo de Sistemas Informáticos'
subtitle: 'Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2019/2020'
theme: jekyll-theme-midnight
#theme: jekyll-theme-time-machine
# theme: jekyll-theme-hacker
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate fatal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-leap-day
description: '3º. 2º cuatrimestre. Itinerario de Tecnologías de la Información. Grado en Ingeniería Informática. Curso 2019/2020'
acronym: DSI
base_url: ''
url: https://ull-esit-dsi-1819.github.io/dsi-1819/
future: true
show_downloads: false
disqus: 
  url: https://desarrollo-de-sistemas-informaticos.disqus.com/embed.js
  comments: true
repo: ULL-ESIT-DSI-1819/dsi-1819
logo: DSIlogo.png
teacher: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
campus_virtual: https://campusvirtual.ull.es/1920/course/view.php?id=201911055
tareas: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201911055
calificador: https://campusvirtual.ull.es/1920/grade/report/grader/index.php?id=201911055
participantes: https://campusvirtual.ull.es/1920/user/index.php?id=201911055
foros: https://campusvirtual.ull.es/1920/mod/forum/index.php?id=201911055
bull_permanente: https://puntoq.ull.es/permalink/f
github_classroom: https://classroom.github.com/classrooms/53047716-ull-esit-dsi-1920
guia_docente: https://www.ull.es/apps/guias/guias/view_subject_guide/139263524/
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
calendario_grado: https://riull.ull.es/xmlui/bitstream/handle/915/14312/Calendario%20de%20Grado%20continuaci%C3%B3n%20actualizado.pdf
horarios_examenes_ii: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/#tercero
horarios_tercero_2c_TI: https://docs.google.com/document/d/1XHFUAiuECAEAPTZvdsn8aJTCAV3jRovC8Px24HgcfyQ/edit
tutorias_departamento: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
google_calendar: https://calendar.google.com/calendar/b/2/embed?showPrint=0&amp;mode=AGENDA&amp;height=400&amp;wkst=2&amp;hl=es&amp;bgcolor=%23cc66cc&amp;src=ull.edu.es_2vro0m6bohfet5n9emce1btblc%40group.calendar.google.com&amp;color=%23182C57&amp;ctz=Atlantic%2FCanary
books_shared: https://github.com/ULL-ESIT-DSI-1920/books-shared
organization:
  url: https://github.com/ULL-ESIT-DSI-1920/
  name: ULL-ESIT-DSI-1920
  master: https://github.com/ULL-ESIT-DSI-1819/dsi-1819/tree/master/
temas:
  - title: 'Tema 0: Presentación'
    url: tema0-presentacion/index.html
    hover: 'Presentación'
  - title: 'Tema 1: Introducción a los Entornos de Trabajo, Herramientas, Pruebas, Integración, Calidad, Diseño y Patrones'
    url: tema1-introduccion/index.html
    hover: 'Intro-a-los-entornos-de-trabajo'
practicas:
  - title: 01pb-gh-campus-expert
    myurl: /tema0-presentacion/pb-gh-campus-expert/
    name: pb-gh-campus-expert
  - title: 02p1-t1-iaas
    myurl: /tema1-introduccion/practicas/p1-t1-iaas/
    name: p1-t1-iaas

exclude: 
  - tema1-introduccion/practicas/p2-t1-c3-file-system/sol-nodejs-filesystem-ch2/ 
  - tema2-async/practicas/p6-t2-microservices/eval/
  - tema3-web/practicas/p8-t3-sessions-and-modules/resources/
